

utils::globalVariables('First Class')
utils::globalVariables('Same Day')
utils::globalVariables('Second Class')
utils::globalVariables('Standard Class')
utils::globalVariables('category')
utils::globalVariables('discount')
utils::globalVariables('discounted')
utils::globalVariables('first_class')
utils::globalVariables('fks_state')
utils::globalVariables('no')
utils::globalVariables('profit')
utils::globalVariables('prop_discounted')
utils::globalVariables('quantity')
utils::globalVariables('region')
utils::globalVariables('rest')
utils::globalVariables('sales')
utils::globalVariables('same_day')
utils::globalVariables('second_class')
utils::globalVariables('ship_mode')
utils::globalVariables('standard_class')
utils::globalVariables('state')
utils::globalVariables('states')
utils::globalVariables('sub_category')
utils::globalVariables('sum_state')
utils::globalVariables('total')
utils::globalVariables('total_profit')
utils::globalVariables('yes')
